---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: devops-superlab
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
configMapGenerator:
  - name: podinfo-config
    literals:
      - PODINFO_UI_MESSAGE=DevOps SuperLab
      - PODINFO_UI_COLOR=#0b1220
